### PR TITLE
DOCS: Add guide to git commits

### PR DESCRIPTION
**Pull request by m-Schlitzer**
Adds a simple guide to git commits, and how to deal with problems.
Tell me what you think.

### CODE REVIEW

**Comment by hockf** [comment]
After reading the guide, I have a few minor improvements:

>... This isn't meant as documentation, it's meant as an overview.
It would sound better if you changed it to the following:
"This isn't meant as a documentation, it's meant to be an overview."

>+If you make any style changes or renaming variables, turn it into a "fixup" commit for
 +the part you correct, this way we don't bloat our commit history up with minor changes.
A slightly more elegant phrasing for this part would be:
"If you are making any style changes or rename any variables, turning it into a "fixup" commit for the part you're correcting 
would prevent our commit history from bloating up with minor changes."

 >+Well, you f'ed it hard now haven't you? Probably already opened a pr?
This line has a few small mistakes in it, the better sentence would be:
Well, you f'ed it up hard now, didn't you? Probably already opened a pr?

**Comment by hockf** [comment]
After reading the guide, I have a few minor improvements:

>... This isn't meant as documentation, it's meant as an overview.

It would sound better if you changed it to the following:
"This isn't meant as a documentation, it's meant to be an overview."

>+If you make any style changes or renaming variables, turn it into a "fixup" commit for
 +the part you correct, this way we don't bloat our commit history up with minor changes.

A slightly more elegant phrasing for this part would be:
"If you are making any style changes or rename any variables, turning it into a "fixup" commit for the part you're correcting 
would prevent our commit history from bloating up with minor changes."

 >+Well, you f'ed it hard now haven't you? Probably already opened a pr?

This line has a few mistakes in it, the correct sentence would be:
Well, you f'ed it up hard now, didn't you? Probably already opened a pr?

**Comment by hockf** [comment]
After reading the guide, I have a few minor improvements:

>... This isn't meant as documentation, it's meant as an overview.

It would sound better if you changed it to the following:
"This isn't meant as a documentation, it's meant to be an overview."

>+If you make any style changes or renaming variables, turn it into a "fixup" commit for
 +the part you correct, this way we don't bloat our commit history up with minor changes.

A slightly more elegant phrasing for this part would be:
"If you are making any style changes or rename any variables, turning it into a "fixup" commit 
for the part you're correcting would prevent our commit history from bloating up with minor changes."

 >+Well, you f'ed it hard now haven't you? Probably already opened a pr?

This line has a few mistakes in it, the correct sentence would be:
Well, you f'ed it up hard now, didn't you? Probably already opened a pr?

**Comment by m-Schlitzer** [comment]
Thank you for your feedback, the phrasing is better your way, I'll change it tonight.
Also, if you have anymore feedback, let me know.

**Comment by dreisen** [comment]
lgtm

**Pull request merged**
